{% set name = "xaitk-saliency" %}
{% set version = "0.14.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xaitk_saliency-{{ version }}.tar.gz
  sha256: 59c9e4a926379e818b78a2bd18e9df9cbd099cd4a027320527cdcadfafe44d57

build:
  entry_points:
    - sal-on-coco-dets = xaitk_saliency.utils.bin.sal_on_coco_dets:sal_on_coco_dets
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.22  # [py<312]
    - numpy >=2.1  # [py>312]
    - scikit-image >=0.25
    - scikit-learn >=1.7
    - smqtk-classifier >=0.20.0
    - smqtk-core >=0.20.0
    - smqtk-descriptors >=0.20.0
    - smqtk-detection >=0.23.0
    - scipy >=1.15.0
    - click >=8.0.3
    - setuptools >=78.1.1
  run_constrained:
    - notebook >=7.2.2
    - matplotlib >=3.4.1
    - papermill >=2.3.3
    - pytorch >=2.2.0
    - torchvision >=0.10.0
    - tqdm >=4.66.3
    - kwcoco >=0.2.18

test:
  imports:
    - xaitk_saliency
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/XAITK/xaitk-saliency
  summary: Visual saliency map generation interfaces and baseline implementations for explainable AI.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eveenhuis
    - Purg
    - bjrichardwebster
    - barry-ravichandran
