{% set name = "xaitk-saliency" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xaitk_saliency-{{ version }}.tar.gz
  sha256: 1ffa1d0c7f49c795bb087d91fd67d344068f37aad0672588782dd2916942ca4b

build:
  noarch: python
  entry_points:
    - sal-on-coco-dets = xaitk_saliency.utils.bin.sal_on_coco_dets:sal_on_coco_dets
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - pip
    - poetry-core
  run:
    - python >=3.8,<4.0
    - numpy >=1.22
    - scikit-image >=0.18.1
    - scikit-learn >=1.2
    - smqtk-classifier >=0.17.0
    - smqtk-core >=0.18.0
    - smqtk-descriptors >=0.16.0
    - smqtk-detection >=0.19.0
    - scipy >=1.8.1
    - click >=8.0.3

test:
  imports:
    - xaitk_saliency
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/XAITK/xaitk-saliency
  summary: Visual saliency map generation interfaces and baseline implementations for explainable AI.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Purg
    - bjrichardwebster
    - barry-ravichandran
