{% set name = "xaitk-saliency" %}
{% set version = "0.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/xaitk_saliency-{{ version }}.tar.gz
  sha256: 211bc7ed58fa82cef2066ae24e42dcf24b08298bccef500953155a28ecad12d4

build:
  entry_points:
    - sal-on-coco-dets = xaitk_saliency.utils.bin.sal_on_coco_dets:sal_on_coco_dets
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python
    - pip
    - poetry-core
  run:
    - python
    - numpy >=1.24.2  # [py<313]
    - numpy >=2.1  # [py>=313]
    - scikit-image >=0.20
    - scikit-learn >=1.5.2
    - smqtk-classifier >=0.20.0
    - smqtk-core >=0.20.0
    - smqtk-descriptors >=0.20.0
    - smqtk-detection >=0.23.0
    - scipy >=1.10.0
    - click >=8.0.3
    - setuptools >=78.1.1,<82.0.0
  run_constrained:
    - notebook >=7.2.2
    - matplotlib >=3.7.1
    - papermill >=2.3.3
    - pytorch >=2.7.0
    - torchvision >=0.22.0
    - tqdm >=4.66.3
    - kwcoco >=0.2.18
    - imagecodecs <2026  # [py<313]
    - imagecodecs >=2026  # [py>=313]

test:
  imports:
    - xaitk_saliency
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/XAITK/xaitk-saliency
  summary: Visual saliency map generation interfaces and baseline implementations for explainable AI.
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - eveenhuis
    - Purg
    - bjrichardwebster
    - barry-ravichandran
